name: CloudOps CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "206858212179"
  ECR_REPOSITORY: cloudops-enterprise-platform/leave-service
  IMAGE_TAG: latest

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Debug GitHub OIDC context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          cache-dependency-path: leave-service/leave-service/pom.xml

      - name: Build Spring Boot application
        working-directory: leave-service/leave-service
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: leave-service/leave-service
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
            $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: DB_URL,DB_USERNAME,DB_PASSWORD
          script: |
            set -e

            AWS_REGION="ap-south-1"
            ECR_REGISTRY="206858212179.dkr.ecr.ap-south-1.amazonaws.com"
            ECR_REPOSITORY="cloudops-enterprise-platform/leave-service"
            CONTAINER_NAME="cloudops-leave-service"

            echo "Logging in to Amazon ECR..."

            aws ecr get-login-password --region $AWS_REGION | \
              docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY

            echo "Pulling latest Docker image..."

            docker pull \
              $ECR_REGISTRY/$ECR_REPOSITORY:latest

            echo "Stopping existing container..."

            docker stop $CONTAINER_NAME || true

            echo "Removing existing container..."

            docker rm $CONTAINER_NAME || true

            echo "Starting new container..."

            docker run -d \
              --name $CONTAINER_NAME \
              -p 8081:8081 \
              -e DB_URL="$DB_URL" \
              -e DB_USERNAME="$DB_USERNAME" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              $ECR_REGISTRY/$ECR_REPOSITORY:latest

            echo "Deployment completed."

            echo "Running containers:"

            docker ps